services:
  orders:
    build:
      context: ..
      dockerfile: orders/Dockerfile

    image: node-orders:1.0
    container_name: node-orders

    ports:
      - "3002:3000"

    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318

    labels:
      observability.service_name: "node-orders"
      observability.environment: "development"

    networks:
      - observability-network

    restart: unless-stopped

networks:
  observability-network:
    external: true